export const SET_LIST_ACCOUNT = 'SET_LIST_ACCOUNT';
export const SET_LIST_BOOK_TITLE = 'SET_LIST_BOOK_TITLE';
export const SET_EDIT_BOOK_DATA = 'SET_EDIT_BOOK_DATA';
export const SET_LIST_AUTHOR = 'SET_LIST_AUTHOR';
export const SET_LIST_NEW_BOOK_TITLE = 'SET_LIST_NEW_BOOK_TITLE';
export const SET_LIST_HOT_BOOK_TITLE = 'SET_LIST_HOT_BOOK_TITLE';